apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsauth
spec:
  selector:
    matchLabels:
      app: tsauth
  template:
    metadata:
      labels:
        app: tsauth
    spec:
      containers:
      - name: tsauth
        image: ticketscalperauth:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m" 
        env:
          - name: ConnectionStrings__DbServer
            valueFrom:
              secretKeyRef:
                name: tssecrets
                key: authDb

---

apiVersion: v1
kind: Service
metadata:
  name: tsauth
  labels:
    app: tsauth
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 80 
  selector:
    app: tsauth
