apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsgateway
spec:
  selector:
    matchLabels:
      app: tsgateway
  template:
    metadata:
      labels:
        app: tsgateway
    spec:
      containers:
      - name: tsgateway
        image: ticketscalpergateway:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m" 
        env:
          - name: GlobalConfiguration__BaseUrl
            valueFrom:
              secretKeyRef:
                name: tssecrets
                key: gatewayBaseUrl

---

apiVersion: v1
kind: Service
metadata:
  name: tsgateway
spec:
  type: LoadBalancer
  selector:
    app: tsgateway
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 80
