apiVersion: apps/v1
kind: Deployment
metadata:
  name: tssales
spec:
  selector:
    matchLabels:
      app: tssales
  template:
    metadata:
      labels:
        app: tssales
    spec:
      containers:
      - name: tssales
        image: ticketscalpersales:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m" 
        env:
          - name: ConnectionStrings__DbServer
            valueFrom:
              secretKeyRef:
                name: tssecrets
                key: salesDb
          - name: gRPC__BaseUrl
            valueFrom:
              secretKeyRef:
                name: tssecrets
                key: grpcBaseUrl

---

apiVersion: v1
kind: Service
metadata:
  name: tssales
  labels:
    app: tssales
spec:
  selector:
    app: tssales
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 80 
