apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsshows
spec:
  selector:
    matchLabels:
      app: tsshows
  template:
    metadata:
      labels:
        app: tsshows
    spec:
      containers:
      - name: tsshows
        image: ticketscalpershows:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m" 
        env:
          - name: ConnectionStrings__DbServer
            valueFrom:
              secretKeyRef:
                name: tssecrets
                key: showsDb


---

apiVersion: v1
kind: Service
metadata:
  name: tsshows
  labels:
    app: tsshows
spec:
  selector:
    app: tsshows
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 80 
