apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketscalper-shows
spec:
  selector:
    matchLabels:
      app: ticketscalper-shows
  template:
    metadata:
      labels:
        app: ticketscalper-shows
    spec:
      containers:
      - name: ticketscalper-shows
        image: shawnwildermuth/ticketscalpershows:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m" 
      - name: ticketscalper-showsdb
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          - name: SA_PASSWORD
            value: "P@ssw0rd!"
          - name: ACCEPT_EULA
            value: "Y"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m" 

---

apiVersion: v1
kind: Service
metadata:
  name: ticketscalper-shows
spec:
  type: LoadBalancer
  selector:
    app: ticketscalper-shows
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
