apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketscalper-web
spec:
  selector:
    matchLabels:
      app: ticketscalper-web 
  template:
    metadata:
      labels:
        app: ticketscalper-web
    spec:
      containers:
      - name: ticketscalper-web
        image: shawnwildermuth/ticketscalperweb:latest
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" 

---

apiVersion: v1
kind: Service
metadata:
  name: ticketscalper
spec:
  type: LoadBalancer
  selector:
    app: ticketscalper-web
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80