apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsweb
spec:
  selector:
    matchLabels:
      app: tsweb
  template:
    metadata:
      labels:
        app: tsweb
    spec:
      containers:
      - name: tsweb
        image: ticketscalperweb:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" 

---

apiVersion: v1
kind: Service
metadata:
  name: tsweb
spec:
  type: LoadBalancer
  selector:
    app: tsweb
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80