version: '3.4'

services:

# Web Servers 

  # web:
  #   image: shawnwildermuth/ticketscalperweb:latest
  #   build:
  #     context: .
  #     dockerfile: TicketScalper.Web/Dockerfile
    

  showsApi:
    image: shawnwildermuth/ticketscalpershows:latest
    build:
      context: .
      dockerfile: TicketScalper.ShowsAPI/Dockerfile

  # salesApi:
  #   image: shawnwildermuth/ticketscalpersales:latest
  #   build:
  #     context: .
  #     dockerfile: TicketScalper.SalesAPI/Dockerfile

  # authApi:
  #   image: shawnwildermuth/ticketscalperauth:latest
  #   build:
  #     context: .
  #     dockerfile: TicketScalper.AuthAPI/Dockerfile

# Databases

  # showsDb: 
  #   image: "mcr.microsoft.com/mssql/server:2019-latest"
  #   environment:
  #       SA_PASSWORD: "P@ssw0rd!"
  #       ACCEPT_EULA: "Y"

  # salesDb:
  #   image: "mcr.microsoft.com/mssql/server:2019-latest"
  #   environment:
  #       SA_PASSWORD: "P@ssw0rd!"
  #       ACCEPT_EULA: "Y"

  # authDb:
  #   image: "mcr.microsoft.com/mssql/server:2019-latest"
  #   environment:
  #       SA_PASSWORD: "P@ssw0rd!"
  #       ACCEPT_EULA: "Y"

# GATEWAY 

  # gateway:
  #   image: shawnwildermuth/ticketscalpergateway
  #   build:
  #     context: .
  #     dockerfile: TicketScalper.Gateway/Dockerfile

