apiVersion: v1
kind: Secret
metadata:
  name: tssecrets
type: Opaque
stringData:
  salesDb: "Data Source=host.docker.internal;Initial Catalog=SalesDb;User ID=sa;Password=P@ssw0rd!;Connect Timeout=10;Encrypt=False;"
  authDb: "Data Source=host.docker.internal;Initial Catalog=AuthDb;User ID=sa;Password=P@ssw0rd!;Connect Timeout=10;Encrypt=False;"
  showsDb: "Data Source=host.docker.internal;Initial Catalog=ShowsDb;User ID=sa;Password=P@ssw0rd!;Connect Timeout=10;Encrypt=False;"
  grpcBaseUrl: "http://tsshows:5003"
  gatewayBaseUrl: "http://localhost:8889/"
